// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TecLibrasApi.Infra;

#nullable disable

namespace TecLibrasApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260908014550_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TecLibrasApi.Domain.Models.Sinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_sinal");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_publicacao");

                    b.Property<string>("DescricaoSinal")
                        .HasColumnType("longtext")
                        .HasColumnName("descricao_sinal");

                    b.Property<int?>("IdInterprete")
                        .HasColumnType("int")
                        .HasColumnName("id_interprete");

                    b.Property<string>("TermoTi")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("termo_ti");

                    b.HasKey("Id");

                    b.HasIndex("IdInterprete");

                    b.ToTable("sinais", (string)null);
                });

            modelBuilder.Entity("TecLibrasApi.Domain.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_criacao");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("IdGoogle")
                        .HasColumnType("longtext")
                        .HasColumnName("id_google");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("USUARIO")
                        .HasColumnName("perfil");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext")
                        .HasColumnName("senha");

                    b.Property<string>("TokenRecuperacao")
                        .HasColumnType("longtext")
                        .HasColumnName("token_recuperacao");

                    b.HasKey("Id");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("TecLibrasApi.Domain.Models.Sinal", b =>
                {
                    b.HasOne("TecLibrasApi.Domain.Models.Usuario", "Interprete")
                        .WithMany()
                        .HasForeignKey("IdInterprete")
                        .HasConstraintName("fk_interprete");

                    b.OwnsOne("TecLibrasApi.Domain.Models.Midia", "Imagem", b1 =>
                        {
                            b1.Property<int>("SinalId")
                                .HasColumnType("int");

                            b1.Property<string>("Formato")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("imagem_formato");

                            b1.Property<long>("Tamanho")
                                .HasColumnType("bigint")
                                .HasColumnName("imagem_tamanho");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("imagem_url");

                            b1.HasKey("SinalId");

                            b1.ToTable("sinais");

                            b1.WithOwner()
                                .HasForeignKey("SinalId");
                        });

                    b.OwnsOne("TecLibrasApi.Domain.Models.Midia", "ImagemSecundaria", b1 =>
                        {
                            b1.Property<int>("SinalId")
                                .HasColumnType("int");

                            b1.Property<string>("Formato")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("imagem_secundaria_formato");

                            b1.Property<long>("Tamanho")
                                .HasColumnType("bigint")
                                .HasColumnName("imagem_secundaria_tamanho");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("imagem_secundaria_url");

                            b1.HasKey("SinalId");

                            b1.ToTable("sinais");

                            b1.WithOwner()
                                .HasForeignKey("SinalId");
                        });

                    b.OwnsOne("TecLibrasApi.Domain.Models.Midia", "Video", b1 =>
                        {
                            b1.Property<int>("SinalId")
                                .HasColumnType("int");

                            b1.Property<string>("Formato")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("video_formato");

                            b1.Property<long>("Tamanho")
                                .HasColumnType("bigint")
                                .HasColumnName("video_tamanho");

                            b1.Property<string>("Url")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("video_url");

                            b1.HasKey("SinalId");

                            b1.ToTable("sinais");

                            b1.WithOwner()
                                .HasForeignKey("SinalId");
                        });

                    b.Navigation("Imagem")
                        .IsRequired();

                    b.Navigation("ImagemSecundaria");

                    b.Navigation("Interprete");

                    b.Navigation("Video")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
